# Generated by Django 5.1.5 on 2025-02-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_remove_reviews_movie_remove_reviews_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=255),
        ),
    ]
